### ISSUE TITLE
convert single table to flat transposition format

### ISSUE THREAD

**Issue by oschulte** [sfu-cl-lab/etl-outlier-detection#2]
Definition of the problem

+ Input: Suppose you have a database table formatted like this

id | mult | h1 | h2 |
----|----|----|----|
100| 22| a | 1 |
100| 13 | b | 2 |
200 | 11 | a | 1 |
200 | 15 | b | 2|

+ Output: We want to transpose this to get a table formatted like this

id | (a,1) | (b,2) |
---| ---- | -----|
100 | 22 | 13 |
200 | 11 | 15 |

+ this tutorial link may be helpful https://oschulte.github.io/srl-tutorial-slides/ch6-anomaly-supplement.pptx
+ also we have code that should do this (more or less), see flat table code in repository

**Comment by oschulte** [comment]
Steps

[x ] design pseudo-code (perhaps check flat table code in repository)
[x ] run on single ct-table

**Comment by JanyQZ** [comment]
@oschulte  Hi Oliver, now I am able to get all the MULT number of different ID based on different situations. For each ID it has different instance from others, so it's hard to find a valid column name for every ID to use. Because if we choose each instance as a new column, there will be hundreds of columns. Do you have any suggestion to solve this problem?

**Comment by oschulte** [comment]
hm, let's discuss today to  make sure I understand. Have you checked how Nicole dealt with this in the flat-table generator code?
